-- liquibase formatted sql

-- changeset ningz:business_identity-alloy_journey_outcome
create table business_identity.business_identity.alloy_journey_outcome
(
    request_token                        varchar(36)                                                                                                                                                                                                                                                    not null,
    timestamp_request                    timestamp                                                                                                                                                                                                                                                      null,
    type_env                             varchar(64)                                                                                                                                                                                                                                                    null,
    description                          varchar(128)                                                                                                                                                                                                                                                   null,
    journey_application_token            varchar(36)                                                                                                                                                                                                                                                    null,
    type_journey                         varchar(40)                                                                                                                                                                                                                                                    null,
    external_partner_id                  varchar(64)                                                                                                                                                                                                                                                    null,
    org_uuid                             varchar(36)                                                                                                                                                                                                                                                    null,
    reason                               varchar(64)                                                                                                                                                                                                                                                    null,
    reasons                              longtext                                                                                                                                                                                                                                                       null,
    timestamp_journey                    timestamp                                                                                                                                                                                                                                                      null,
    outcome                              varchar(16)                                                                                                                                                                                                                                                    null,
    evaluation_token                     varchar(24)                                                                                                                                                                                                                                                    null,
    case_token                           varchar(24)                                                                                                                                                                                                                                                    null,
    entity_token                         varchar(24)                                                                                                                                                                                                                                                    null,
    entity_application_token             varchar(24)                                                                                                                                                                                                                                                    null,
    node_id                              varchar(45)                                                                                                                                                                                                                                                    null,
    node_name                            varchar(64)                                                                                                                                                                                                                                                    null,
    node_position                        varchar(45)                                                                                                                                                                                                                                                    null,
    node_type                            varchar(10)                                                                                                                                                                                                                                                    null,
    node_config_application_token        varchar(24)                                                                                                                                                                                                                                                    null,
    node_config_workflow_token           varchar(24)                                                                                                                                                                                                                                                    null,
    node_config_application_version_id   int                                                                                                                                                                                                                                                            null,
    node_config_workflow_version_id      int                                                                                                                                                                                                                                                            null,
    node_config_workflow_type            varchar(16)                                                                                                                                                                                                                                                    null,
    node_config_workflow_current_version int                                                                                                                                                                                                                                                            null,
    node_config_journey_action_id        int                                                                                                                                                                                                                                                            null,
    node_config_action_name              varchar(16)                                                                                                                                                                                                                                                    null,
    node_config_action_type              varchar(16)                                                                                                                                                                                                                                                    null,
    node_config_action_version           int                                                                                                                                                                                                                                                            null,
    node_config_outcome                  varchar(16)                                                                                                                                                                                                                                                    null,
    external_entity_id                   varchar(24)                                                                                                                                                                                                                                                    null,
    create_date                          timestamp(6) default CURRENT_TIMESTAMP(6)                                                                                                                                                                                                                      null,
    change_date                          timestamp(6) default CURRENT_TIMESTAMP(6)                                                                                                                                                                                                                      null on update CURRENT_TIMESTAMP(6),
    status                               enum ('started_application', 'data_request_evaluation', 'pending_review', 'pending_documents', 'pending_step_up', 'completed_review', 'completed_evaluation', 'completed_review_journey_application', 'completed_application', 'application_expired', 'error') null,
    primary key (request_token)
);


-- rollback DROP TABLE business_identity.alloy_journey_outcome