name: main

on:
   push:
     branches:
        - main
     paths:
        - 'sql/**'
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: Run 'Liquibase status' in a Docker Container	    
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.URL }} --changeLogFile=/sql/master.xml --username=${{ secrets.USERNAME }} --password=${{ secrets.PASSWORD }} --defaultSchemaName=${{ secrets.SCHEMA }} status
 
    
    - name: Run 'Liquibase update' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.URL }} --changeLogFile=/sql/master.xml --username=${{ secrets.USERNAME }} --password=${{ secrets.PASSWORD }} --defaultSchemaName=${{ secrets.SCHEMA }} --logLevel=debug update
 

        
        
