name: main

on:
  workflow_dispatch:
    push:
     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    
    variables:
      URL: jdbc:mysql://localhost:3306/onboarding
      USERNAME: root
      PASSWORD: Bestfrnd24!!
      DRIVER: com.mysql.cjdbc.Driver   
      SCHEMA: onboarding
    
    steps: 
    - uses: actions/checkout@v2
    
    - name: Run 'Liquibase status' in a Docker Container	    
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=$URL --changeLogFile=master.xml --username=$USERNAME --password=$PASSWORD --driver=$DRIVER--defaultSchemaName=$SCHEMA status
 
    
    - name: Run 'Liquibase update' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=$URL --changeLogFile=master.xml --username=$USERNAME --password=$PASSWORD --driver=$DRIVER--defaultSchemaName=$SCHEMA  --logLevel=debug update
 

        
        
